const nodeMail = require("nodemailer");
const transporter = nodeMail.createTransport({
    //host: 'smtp.ethereal.email',
    host: 'rprotravels.com.ng',
    port: 465,
    auth: {
        //user: 'tristian.hickle9@ethereal.email',
        user: 'info@rprotravels.com.ng',
       // pass: 'Wz1M1qjnNGGASAQzKj'
        pass: 'Nn0Ontde4DHf'
    }
  });


const getSendMail = async (bodyMsg,mailto,subj,name)=>{

    var htmlContent ='<!doctype html> <html xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office"> <head> <title> info@rprotravels.com.ng Email </title> <meta http-equiv="X-UA-Compatible" content="IE=edge"> <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"> <meta name="viewport" content="width=device-width, initial-scale=1"> <style type="text/css"> #outlook a { padding: 0; } .ReadMsgBody { width: 100%; } .ExternalClass { width: 100%; } .ExternalClass * { line-height: 100%; } body { margin: 0; padding: 0; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; } table, td { border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; } img { border: 0; height: auto; line-height: 100%; outline: none; text-decoration: none; -ms-interpolation-mode: bicubic; } p { display: block; margin: 13px 0; } </style> <!--[if !mso]><!--> <style type="text/css"> @media only screen and (max-width:480px) { @-ms-viewport { width: 320px; } @viewport { width: 320px; } } </style> <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet" type="text/css"> <style type="text/css"> @import url(https://fonts.googleapis.com/css?family=Roboto:300,400,500,700); </style> <style type="text/css"> @media only screen and (min-width:480px) { .mj-column-per-100 { width: 100% !important; max-width: 100%; } .mj-column-per-50 { width: 50% !important; max-width: 50%; } } </style> <style type="text/css"> @media only screen and (max-width:480px) { table.full-width-mobile { width: 100% !important; } td.full-width-mobile { width: auto !important; } } </style> </head> <body style="background-color:#EDF2F9;"> <!-- Change the color to your app brand color --> <div style="display:none;font-size:1px;color:#ffffff;line-height:1px;max-height:0px;max-width:0px;opacity:0;overflow:hidden;"> info@rprotravesl.com.ng Email </div> <div style="background-color:#EDF2F9;"> <!-- Change the color to your app brand color --> <!-- Email Header Ends-->'

    htmlContent += '<div style="background:#32323A;background-color:#32323A;Margin:0px auto;max-width:600px;"> <table align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="background:#4d4d4d;background-color:#4d4d4d;width:100%;"> <tbody> <tr> <td style="direction:ltr;font-size:0px;padding:20px 0;text-align:center;vertical-align:top;"> <div class="mj-column-per-100 outlook-group-fix" style="font-size:13px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;"> <table border="0" cellpadding="0" cellspacing="0" role="presentation" style="vertical-align:top;" width="100%"> <tr> <td align="center" style="font-size:0px;padding:10px 25px;word-break:break-word;"> <div style="font-family:\'Roboto Condensed\', Helvetica, Arial, sans-serif;font-size:26px;font-weight:400;line-height:24px;text-align:center;color:#ffffff;"> <div style="display:block;margin:auto;"> <img height="30" src="https://rprotravels.com.ng/assets/img1/logo2.jpg" style="border-radius:3px; margin:3px; width:60px; height:50px" width="30" /> </div> <b style="margin-top:30px"> rProtravels Limited </b> </div> </td> </tr> </table> </div> </td> </tr> </tbody> </table> </div>';

    htmlContent += '<div class="body-section" style="-webkit-box-shadow: 0 25px 50px rgba(8,21,66,.06); -moz-box-shadow: 0 25px 50px rgba(8,21,66,.06); box-shadow: 0 25px 50px rgba(8,21,66,.06); Margin: 0px auto; max-width: 600px;"> <table align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="width:100%;"> <tbody> <tr> <td style="direction:ltr;font-size:0px;padding:20px 0;padding-bottom:0;padding-top:0;text-align:center;vertical-align:top;"> <div style="background:#ffffff;background-color:#ffffff;Margin:0px auto;max-width:600px;"> <table align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="background:#ffffff;background-color:#ffffff;width:100%;"> <tbody> <tr> <td style="direction:ltr;font-size:0px;padding:15px;text-align:center;vertical-align:top;"> <div class="mj-column-per-100 outlook-group-fix" style="font-size:13px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;"> <table border="0" cellpadding="0" cellspacing="0" role="presentation" style="border:1px solid #dddddd;vertical-align:top;" width="100%">  <td style="font-size:0px;padding:0 20px;word-break:break-word;"> <p style="border-top:dashed 1px lightgrey;font-size:1;margin:0px auto;width:100%;"> </p> </td> </tr> <tr> <td align="left" style="font-size:0px;padding:20px;word-break:break-word;"> <div style="font-family:\'Roboto Condensed\', sans-serif;font-size:16px;font-weight:400;line-height:24px;text-align:left;color:#000000;">  <p>'+bodyMsg+'</p> </div> </td> </tr> <tr> <td align="left" vertical-align="middle" style="font-size:0px;padding:10px 25px;word-break:break-word;"> <table border="0" cellpadding="0" cellspacing="0" role="presentation" style="border-collapse:separate;width:150px;line-height:100%;"> </table> </td> </tr> </table> </div> </td> </tr> </tbody> </table> </div>';

    htmlContent +='<!-- Email Footer Start--> <div style="background:#ffffff;background-color:#ffffff;Margin:0px auto;max-width:600px;"> <table align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="background:#ffffff;background-color:#ffffff;width:100%;"> <tbody> <tr> <td style="direction:ltr;font-size:0px;padding:0 15px 0 15px;text-align:center;vertical-align:top;"> <div class="mj-column-per-100 outlook-group-fix" style="font-size:13px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;"> <table border="0" cellpadding="0" cellspacing="0" role="presentation" style="vertical-align:top;" width="100%"> <tr> <td align="left" style="font-size:0px;padding:10px 25px;word-break:break-word;"> <div style="font-family:, Helvetica, Arial, sans-serif;font-size:14px;font-weight:400;line-height:24px;text-align:left;color:#637381;">If you need support, contact: info@rprotravels.com.ng</div> </td> </tr> <tr> <td align="left" style="font-size:0px;padding:10px 25px;padding-bottom:0;word-break:break-word;"> <div style="font-family:, Helvetica, Arial, sans-serif;font-size:14px;font-weight:400;line-height:24px;text-align:left;color:#637381;"><strong>rprotravels Team</strong></div> </td> </tr> <tr> <td align="left" style="font-size:0px;padding:10px 25px;word-break:break-word;"> <div style="font-family:, Helvetica, Arial, sans-serif;font-size:14px;font-weight:400;line-height:24px;text-align:left;color:#637381;"> Replies to this message are undeliverable and will not reach the <strong>rprotravels Team</strong>. Please do not reply.<br> </div> </td> </tr> </table> </div> </td> </tr> </tbody> </table> </div> </td> </tr> </tbody> </table> </div> <table align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="width:100%;"> <tbody> <tr> <td> <div style="Margin:0px auto;max-width:600px;"> <table align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="width:100%;"> <tbody> <tr> <td style="direction:ltr;font-size:0px;padding:20px 0;text-align:center;vertical-align:top;"> <div style="Margin:0px auto;max-width:600px;"> <table align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="width:100%;"> <tbody> <tr> <td style="direction:ltr;font-size:0px;padding:20px 0;text-align:center;vertical-align:top;">';

    htmlContent +='<div class="mj-column-per-100 outlook-group-fix" style="font-size:13px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;"> <table border="0" cellpadding="0" cellspacing="0" role="presentation" width="100%"> <tbody> <tr> <td style="vertical-align:top;padding:0;"> <table border="0" cellpadding="0" cellspacing="0" role="presentation" style="" width="100%"> <tr> <td align="center" style="font-size:0px;padding:0;word-break:break-word;"> <table align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="float:none;display:inline-table;"> <tr> <td style="padding:4px;"> <table border="0" cellpadding="0" cellspacing="0" role="presentation" style="background:#0000b2;border-radius:3px;width:30px;"> <tr> <td style="font-size:0;height:30px;vertical-align:middle;width:30px; color:#000000"> <a href="https://web.facebook.com/rprotravels?_rdc=1&_rdr" target="_blank">';

    htmlContent+='<img height="30" src="https://www.mailjet.com/images/theme/v1/icons/ico-social/facebook.png" style="border-radius:3px;" width="30"> </a> </td> </tr> </table> </td> </tr> </table> <table align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="float:none;display:inline-table;"> <tr> <td style="padding:4px;"> <table border="0" cellpadding="0" cellspacing="0" role="presentation" style="background:#0000b2;border-radius:3px;width:30px;"> <tr> <td style="font-size:0;height:30px;vertical-align:middle;width:30px;"> <a href="https://www.instagram.com/rprotravels.pro/" target="_blank"> <img height="30" src="https://www.mailjet.com/images/theme/v1/icons/ico-social/instagram.png" style="border-radius:3px;" width="30"> </a> </td> </tr> </table> </td> </tr> </table> <table align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="float:none;display:inline-table;"> <tr> <td style="padding:4px;"> <table border="0" cellpadding="0" cellspacing="0" role="presentation" style="background:#0000b2;border-radius:3px;width:30px;"> <tr> <td style="font-size:0;height:30px;vertical-align:middle;width:30px;"> <a href="https://twitter.com/rprotravels" target="_blank"> <img height="30" src="https://www.mailjet.com/images/theme/v1/icons/ico-social/twitter.png" style="border-radius:3px;" width="30"> </a> </td> </tr> </table> </td> </tr> </table> </td> </tr> <tr> <td align="center" style="font-size:0px;padding:10px 25px;word-break:break-word;"> <div style="font-family:, Helvetica, Arial, sans-serif;font-size:11px;font-weight:400;line-height:16px;text-align:center;color:#445566;">Copyright rprotravels Limited - All Rights Reserved.</div> </td> </tr> </table> </td> </tr> </tbody> </table> </div> </td> </tr> </tbody> </table> </div> </td> </tr> </tbody> </table> </div> </td> </tr> </tbody> </table> </div> </body> </html>';
             
  
            
    const info = await transporter.sendMail({
        from: '"rProTravels Limited" <info@rprotravels.com.ng>', // sender address
        to: mailto, // list of receivers
        subject: subj, // Subject line
        // text: "Hello world?", // plain text body
        html:  htmlContent, // html body
    });

  //console.log("Message sent: %s", info.messageId);
    //console.log(year+"-"+month+"-"+day);
    return info.messageId;

}

module.exports ={
    getSendMail
}